west:
  url: https://github.com/zephyrproject-rtos/west
  version: v0.8.0

manifest:
  self:
    path: gametoy
  defaults:
    remote: zephyr
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: github
      url-base: git@github.com:adri1mart1
  projects:
    - name: zephyr
      remote: zephyr
      revision: v3.7.0
      import:
        name-allowlist:
          - segger
          - hal_nordic
          - hal_st
          - hal_stm32
          - cmsis
      west-commands: scripts/west-commands.yml
